[package]
name = "helm-resource"
version = "0.1.0"
authors = ["Michael Eden <themichaeleden@gmail.com>"]

[dependencies]
serde = "^0.8.22"
serde_derive = "^0.8.22"
serde_json = "^0.8.4"
helm-api = { path = "../helm-api" }


[[bin]]
name = "check"
path = "src/bin/check.rs"

[[bin]]
name = "in"
path = "src/bin/in.rs"

[[bin]]
name = "out"
path = "src/bin/out.rs"
