platform: linux

image_resource:
  type: docker-image
  source:
    repository: liuchong/rustup
    tag: 'beta-musl'

inputs:
- name: helm-resource

run:
  path: cargo
  dir: helm-resource
  args:
    - build
    - --release
    - --target=x86_64-unknown-linux-musl
